//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int GroupId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string AdminName { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    }
}
