//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int GroupId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> DriverId { get; set; }
        public Nullable<int> MatchStatus { get; set; }
    }
}
