//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RideDBEntities : DbContext
    {
        public RideDBEntities()
            : base("name=RideDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<RafaelMember> RafaelMembers { get; set; }
        public virtual DbSet<RideRequest> RideRequests { get; set; }
        public virtual DbSet<Ride> Rides { get; set; }
        public virtual DbSet<RideUser> RideUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
