//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RafaelMember
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string PhoneNum { get; set; }
        public string HomeAddress { get; set; }
        public string WorkSite { get; set; }
        public Nullable<int> HasCar { get; set; }
    }
}
